version: '3.4'

services:
  blackburdsecurity:
    image: blackburdsecurity
    # depends_on: 
    #   - kafka
    build:
      context: ./Flask_Video_Streaming_for_Object_Detection/
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker/
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.43.91:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  activemq:
    image: ivonet/activemq
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    environment:
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    - ACTIVEMQ_ENABLED_AUTH=true
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=secret
#    - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
#    - ACTIVEMQ_WRITE_LOGIN=producer
#    - ACTIVEMQ_WRITE_PASSWORD=secret
#    - ACTIVEMQ_READ_LOGIN=consumer
#    - ACTIVEMQ_READ_PASSWORD=secret
#    - ACTIVEMQ_JMX_LOGIN=jmx
#    - ACTIVEMQ_JMX_PASSWORD=secret
#    - ACTIVEMQ_USER_LOGIN=user
#    - ACTIVEMQ_USER_PASSWORD=user
    volumes:
    - ./volumes/log/activemq:/var/log/activemq
